language: python
dist: xenial
notifications:
  slack:
    secure: fzPTPyFF7x8I2kzK6egz+KHHUqK5WMD3/lk8nMWT4uaig5Fymk+PAS2n1uYisc1qFnvdbjrI6BwLph9s40t4+v5ciRhSg/nQhc5O0fhT7z3OtRBgT3+d2mXsD8eePcFO6d/LIXjxrm2OrxVZgKOkm0o8sfOJJRWdXEwU+KxBImHMGX6u93dwEY+XmhfqWebrlKf8o/1UobOYMl2C8U8eaJpchp7snW//OrtL/Eq+IyMDHsXQxxYto6g6qirzvAs2qJHLjHRcuyXffFPcwwWHFwXhNguE4DZr+5nekWTQOnlWt3z3n4suviNLuRtiq6KxI+KReBzb1qbM3kVuCaVlJzckSV5VSGPyfUX/Usk/N0rfNvR2i2cA5q8sl0bXukpRYy5YcgQX2EzB4jonUUF4ACbMC/Vmi8hHXNbcZbrusFpBKwuqQwcW6UG5PKNyYDj1M6wu0kOIkqZk2FBIIvi/wpK4znpsLi0Xb4RaNp0R2yL2E4XwPx5aoP+da8KLAfqJk7PujIo/vA6tqi6CnNEtfn+cHLCaUgGmk3cwBFSpvzZgiBAa0yN6YqcohjhYDnVazmKjj0wIYKK7wDWNGJ/zVNfv1iB9QQVkjkofN8WTJ0xditGll8PnDwoBneRXTRykipe/b/KNMbBp59WDUx9PK6BBs+XjsBmpGs8MqldhiFY=
  on_success: change
  on_failure: always
matrix:
  include:
  - python: 2.7
before_install:
- sudo apt-get update
install:
- pip install -r requirements.txt
script:
- pytest --cov=stuff --cov=test
- flake8 . --exit-zero
after_success:
- coveralls
