language: python
dist: xenial
notifications:
  slack:
    secure: b1VxEZ9SaAnQlTUYvYuJVPenq9nr8XrgPO2cDx6gKh9shUzWMTt69zuhycloHdkyi9XpHJGm9kpzEfBEKu5fa6ZwvNvadf4/MdHn30IOhOyd4n62D29c353FsmIFnI8b/Djsn0B3bJcWeRmLFOeh3LkZ3BKHUO/GNsrNoo4F5mk+lfw6oJGPNvi5ubhlWrb/aoTb32q0J+2/i8gOP+TP8EKFGOSPQuTFTQvJZL1C1D2xT+c66AFdBkq8h6SD8rer76X8xFEZPWSlOJqgZRYIvXs1/D3g12Y3Wr5s7AlZPmZVLQbs9/aqa64HcEgYL5JqSSsUlBsmBOi+Vi6DMhG9/jlZvwmEpFz49ATddaJpEQTAre/iYmKD4pZttoI/VAVegGgQgsIKPcJBbYTDMe8dBooLRlg9p+FlRK4RCd4uLHJ5DYxs0EAEk0aANhhTJ7Zxatul2wupQZqJUB7/iSDvieKIWcuh5sQcj0CmAtw5lu6WE6KLKlSQ54AH38AkbS4ReVplomPaIubXXCAqb4m+SMi2n3gfi3Yy2G+h7Am15SjPnHkK7MJSiuCG8R2lj/K9F8UXCw6xBvW6dvpzS18z/o3ksyrn7mq5nNP/TOSB4r0sZ0FHX/gXpd452dYHGTUekXdC5n02v2/kuK3Nkb7IF/emSi19PYapBPQlv6xdOG0=
  on_success: change
  on_failure: always
matrix:
  include:
  - python: 2.7
before_install:
- sudo apt-get update
install:
- pip install -r requirements.txt
script:
- pytest --cov=stuff --cov=test
- flake8 . --exit-zero
after_success:
- coveralls
